version: '3'

services:
  umleditor:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./umleditor:/usr/local/umleditor
    environment:
      - DISPLAY=:99
    privileged: true
    cap_add:
      - SYS_ADMIN
